apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "teams-status-monitor.fullname" . }}-backend-conf
data:
  DBHost: {{ .Values.redis.url }}
  DBPort: {{ quote (default "34726" .Values.redis.port) }}
  logLevel: {{ quote (default "INFO" .Values.common.log_level) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "teams-status-monitor.fullname" . }}-nginx-conf
data:
  default.conf: |
{{ tpl (.Files.Get "config/default.conf") . | indent 4}}
