{
 "title": "Teams Meeting Status",
 "tags": [ "Meeting" ],
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "user",
    "label": "user",
    "query": {
     "query": "label_values(teams_meeting_status,user)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Meeting Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without (container,endpoint,instance,job,namespace,pod,service) (teams_meeting_status{user=\"$user\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Meeting Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (container,endpoint,instance,job,namespace,pod,service) (teams_meeting_status{user=\"$user\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Meeting Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum without (container,endpoint,instance,job,namespace,pod,service) (total_teams_meeting_time{user=\"$user\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service last updated",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - service_uptime{job=~\"teams-status-monitor-service-backend\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests QPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "sum without (container,endpoint,exported_endpoint,instance,job,namespace,pod,service) (label_replace(rate(service_http_request_count_total{job=~\"teams-status-monitor-service-backend\"}[1m]), \"api_endpoint\", \"$1\", \"exported_endpoint\", \"(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_uptime{job=~\"teams-status-monitor-service-backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request size (bytes) per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without (container,endpoint,exported_endpoint,instance,job,namespace,pod,service) (label_replace(rate(service_http_request_size_bytes_sum{job=~\"teams-status-monitor-service-backend\"}[1m])\n/\nrate(service_http_request_size_bytes_count{job=~\"teams-status-monitor-service-backend\"}[1m]), \"api_endpoint\", \"$1\", \"exported_endpoint\", \"(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without (container,endpoint,exported_endpoint,instance,job,namespace,pod,service) (label_replace(rate(service_http_request_duration_seconds_sum{job=~\"teams-status-monitor-service-backend\"}[1m])\n/\nrate(service_http_request_duration_seconds_count{job=~\"teams-status-monitor-service-backend\"}[1m]), \"api_endpoint\", \"$1\", \"exported_endpoint\", \"(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}